title: UP20 Blog
author: UP20 Member
email: info@tempdomain.com
description: > # this means to ignore newlines until "baseurl:"
  UP20 is an opensource community project aiming to expand and facilitate social programs
  all around the globe. UP20 members are dedicated to sharing community programs and best
  practices. Find us on github and come share your knowledge with other UP20 members.

# social links
twitter_username: twitter-handle
github_username:  github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

