title: UP20 Project Site
author: UP20 Member
email: temp@UP20.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome traveller, 
  to the UP20 Marketplace for social innovation and sustainability programs.
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

