title: UP20 Project Site
author: UP20 Member
email: temp@UP20.com
description: > # this means to ignore newlines until "baseurl:"
  # Welcome traveller, 
  ### to the UP20 Marketplace for social innovation and sustainability programs.
    
  ## So what's cooking ?
    * UP20 is a marketplace for people with social programs and ideas
    * UP20 is dedicated to address and meet all SDG values by co-creating and related activities.
    
    ## by 2020. Our intent is
    * To create a vivid market-place for social ideas and rograms
    * To support SDG activists everywhere and promote co-creation
    * To learn how to learn and teach how to teach the skills we endorse
    * To strive each moment to pursue happiness for us and our children
  
  Write and publish community programs with awesome social reurn on investments (SROI) and share
  your content on the path to success. Hey, you may even host your site here. 
  You can connect with like-minded folks from all around the globe, and collaborate in this
  _opensource eco-system_ environment. 
  
  Drop us a line and share your ideas. We'll make sure it will appear in your documents reach the masses.
  Specifically those organizations and individuals with access to massive suppoprt, influence and resources.
  
  By all means - this is the best way to expand human co-creation and collaboration state-of-the-art communication.
  Join us in this noble quest to propagate useful information about 'Social Programs That Deliver SDG Values'.
  
  stay tuned frost more

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

